apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}-backup-pv
  namespace: {{ .Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Params.STORAGE }}
