apiVersion: kudo.dev/v1beta1
parameters:
  - name: BACKUP_FILE
    description: "Filename to save the backups to"
    default: "backup.sql"
    displayName: "BackupFile"
    trigger: backup
  - name: BACKUP_DB
    description: "Database to backup.  Defaults to all if undefined"
    default: ""
    displayName: "BackupDB"
    trigger: backup
  - name: PASSWORD
    default: "password"
  - name: RESTORE_FILE
    default: "backup.sql"
    description: "Filename to restore the db from"
    trigger: restore
  - name: RESTORE_DB
    default: ""
    description: "Name of the database to restore to."
    trigger: restore
  - name: PORT
    default: 3306
    description: "Port on which MySQL listens for connections"
  - name: STORAGE
    default: 1Gi
    description: "Size of volume to store MySQL data"
